spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/capstone?verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: jeff
    password: pass

#ClearDB hosting stuff

#
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
